// sample/user_auth/src/pages/App.tsx
import * as React from 'react';

console.log("env=", process.env.NODE_ENV)
//
export default function Page() { 
    return (
    <html>
        <head>
            <title>welcome</title>
            {(process.env.NODE_ENV === "develop") ? (
                <link href="/static/style.css" rel="stylesheet" /> 
            ): (
                <link href="/public/static/style.css" rel="stylesheet" /> 
            )} 
        </head>
        <div id="app"></div>
        {(process.env.NODE_ENV === "develop") ? (
            <script type="module" src="/static/main.js"></script>
        ): (
            <script type="module" src="/public/static/main.js"></script>
        )}
    </html>
    );
}
/*
<link href="/static/main.css" rel="stylesheet" />
*/

// src/pages/App.svelte
<script lang="ts">
//console.log("App.svelte.NODE_ENV=", process.env.NODE_ENV);
//<head>
</script>

<!-- -->
<html>
  <head>
      <meta charSet="utf-8"/>
      <meta name="viewport" content="width=device-width, initial-scale=1"/>
      <title>welcome</title>
      {#if process.env.NODE_ENV === "develop"}
          <link href="/static/style.css" rel="stylesheet" />
      {:else}
          <link href="/public/static/style.css" rel="stylesheet" />
      {/if}
      </head>
  <body>
      <div id="app"></div>
      {#if process.env.NODE_ENV === "develop"}
          <script type="module" src="/static/main.js"></script>
      {:else}
          <script type="module" src="/public/static/main.js"></script>
      {/if}
  </body>
</html>

<style>
</style>
<!--
-->
